baseURL = "/"
languageCode = "en-gb"
title = "Education Funding UK"

[params]
  updatemessage = "updated style and added new home page"

[outputs]
   home = [ "HTML", "JSON" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
